source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.1.5'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt', '~> 2.8'
gem 'jbuilder'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  # Rails 7.1 test runner is incompatible with Minitest 6 (line_filtering.rb ArgumentError)
  gem 'minitest', '~> 5.25'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end
